export const DOC_TYPES = {
    DASHBOARD: 'dashboard',
    ITEMS: 'items',
    BANKING: 'banking',
    CUSTOMERS: 'customers',
    VENDORS: 'vendors',
    QUOTES: 'quotes',
    SO: 'sales-orders',
    INVOICES: 'invoices',
    PAYMENTS_REC: 'payments-received',
    DC: 'delivery-chalans',
    CREDIT_NOTES: 'credit-notes',
    EXPENSES: 'expenses',
    PO: 'purchase-orders',
    BILLS: 'bills',
    PAYMENTS_MADE: 'payments-made',
    PROFORMA: 'proforma-invoices',
    VENDOR_CREDITS: 'vendor-credits',
    USERS: 'users',
    REPORTS: 'reports'
};

export const STORAGE_KEYS = {
    [DOC_TYPES.ITEMS]: 'hub_items',
    [DOC_TYPES.BANKING]: 'hub_banking',
    [DOC_TYPES.CUSTOMERS]: 'hub_customers',
    [DOC_TYPES.VENDORS]: 'hub_vendors',
    [DOC_TYPES.QUOTES]: 'hub_quotes',
    [DOC_TYPES.SO]: 'hub_so',
    [DOC_TYPES.INVOICES]: 'hub_invoices',
    [DOC_TYPES.PAYMENTS_REC]: 'hub_payments_rec',
    [DOC_TYPES.DC]: 'hub_dc',
    [DOC_TYPES.CREDIT_NOTES]: 'hub_credit_notes',
    [DOC_TYPES.EXPENSES]: 'hub_expenses',
    [DOC_TYPES.PO]: 'hub_po',
    [DOC_TYPES.BILLS]: 'hub_bills',
    [DOC_TYPES.PAYMENTS_MADE]: 'hub_payments_made',
    [DOC_TYPES.PROFORMA]: 'hub_proforma',
    [DOC_TYPES.VENDOR_CREDITS]: 'hub_vendor_credits',
    [DOC_TYPES.USERS]: 'hub_users'
};
